-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity axi_slave_lite_reg is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    s_axi_ar_araddr : IN STD_LOGIC_VECTOR (63 downto 0);
    s_axi_ar_arready : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_ar_arvalid : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axi_aw_awaddr : IN STD_LOGIC_VECTOR (63 downto 0);
    s_axi_aw_awready : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_aw_awvalid : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axi_b_bresp : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_b_bready : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axi_b_bvalid : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_r_rdata : OUT STD_LOGIC_VECTOR (63 downto 0);
    s_axi_r_rresp : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_r_rready : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axi_r_rvalid : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_w_wdata : IN STD_LOGIC_VECTOR (63 downto 0);
    s_axi_w_wstrb : IN STD_LOGIC_VECTOR (7 downto 0);
    s_axi_w_wready : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_w_wvalid : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of axi_slave_lite_reg is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "axi_slave_lite_reg_axi_slave_lite_reg,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu19eg-ffvc1760-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.015000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=63,HLS_SYN_LUT=380,HLS_VERSION=2020_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal state1_V : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal waddr_V : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal inner_reg0_V : STD_LOGIC_VECTOR (8 downto 0) := "100100011";
    signal inner_reg1_V : STD_LOGIC_VECTOR (10 downto 0) := "10001010110";
    signal inner_reg2_V : STD_LOGIC_VECTOR (8 downto 0) := "110001001";
    signal inner_reg3_V : STD_LOGIC_VECTOR (11 downto 0) := "101010111100";
    signal state_V : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal raddr_V : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal rdata_V : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal ap_phi_mux_p_Val2_1_phi_fu_227_p14 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal state1_V_load_load_fu_281_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal s_axi_b_bready_read_read_fu_146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal s_axi_w_wvalid_read_read_fu_102_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln45_fu_357_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal s_axi_aw_awvalid_read_read_fu_160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_wready_V_phi_fu_246_p14 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln1348_1_fu_315_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Result_s_fu_323_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_inner_reg0_V_load : STD_LOGIC_VECTOR (8 downto 0);
    signal state_V_load_load_fu_368_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal s_axi_ar_arvalid_read_read_fu_173_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_1_fu_388_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln1348_fu_311_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_inner_reg1_V_load : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_inner_reg2_V_load : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln1348_2_fu_319_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_sig_allocacmp_inner_reg3_V_load : STD_LOGIC_VECTOR (11 downto 0);
    signal s_axi_r_rready_read_read_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln97_fu_372_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal and_ln534_fu_500_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln107_fu_406_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln104_fu_420_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln101_fu_434_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln38_fu_295_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_fu_305_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln107_fu_402_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Result_4_fu_462_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_5_fu_476_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln870_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln674_fu_458_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln124_fu_492_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln534_fu_506_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_141 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    rdata_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_141)) then
                if ((p_Result_1_fu_388_p4 = ap_const_lv2_3)) then 
                    rdata_V <= ap_sig_allocacmp_inner_reg3_V_load;
                elsif ((p_Result_1_fu_388_p4 = ap_const_lv2_0)) then 
                    rdata_V <= zext_ln101_fu_434_p1;
                elsif ((p_Result_1_fu_388_p4 = ap_const_lv2_1)) then 
                    rdata_V <= zext_ln104_fu_420_p1;
                elsif ((p_Result_1_fu_388_p4 = ap_const_lv2_2)) then 
                    rdata_V <= zext_ln107_fu_406_p1;
                end if;
            end if; 
        end if;
    end process;

    state1_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((s_axi_aw_awvalid_read_read_fu_160_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((s_axi_w_wvalid_read_read_fu_102_p2 = ap_const_lv1_0) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                state1_V <= ap_const_lv2_1;
            elsif (((s_axi_b_bready_read_read_fu_146_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                state1_V <= ap_const_lv2_0;
            elsif ((((s_axi_w_wvalid_read_read_fu_102_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((s_axi_b_bready_read_read_fu_146_p2 = ap_const_lv1_0) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                state1_V <= ap_const_lv2_2;
            end if; 
        end if;
    end process;

    state_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                if (((s_axi_r_rready_read_read_fu_218_p2 = ap_const_lv1_1) and (state_V_load_load_fu_368_p1 = ap_const_lv1_1))) then 
                    state_V <= ap_const_lv1_0;
                elsif (((s_axi_ar_arvalid_read_read_fu_173_p2 = ap_const_lv1_1) and (state_V_load_load_fu_368_p1 = ap_const_lv1_0))) then 
                    state_V <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((p_Result_s_fu_323_p4 = ap_const_lv2_0) and (s_axi_w_wvalid_read_read_fu_102_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                inner_reg0_V <= zext_ln1348_1_fu_315_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((p_Result_s_fu_323_p4 = ap_const_lv2_1) and (s_axi_w_wvalid_read_read_fu_102_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    inner_reg1_V(7 downto 0) <= zext_ln1348_fu_311_p1(7 downto 0);    inner_reg1_V(10) <= zext_ln1348_fu_311_p1(10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((p_Result_s_fu_323_p4 = ap_const_lv2_2) and (s_axi_w_wvalid_read_read_fu_102_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                inner_reg2_V <= zext_ln1348_1_fu_315_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((p_Result_s_fu_323_p4 = ap_const_lv2_0)) and not((p_Result_s_fu_323_p4 = ap_const_lv2_1)) and (s_axi_w_wvalid_read_read_fu_102_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    inner_reg3_V(7 downto 0) <= zext_ln1348_2_fu_319_p1(7 downto 0);    inner_reg3_V(9) <= zext_ln1348_2_fu_319_p1(9);    inner_reg3_V(11) <= zext_ln1348_2_fu_319_p1(11);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (s_axi_ar_arvalid_read_read_fu_173_p2 = ap_const_lv1_1) and (state_V_load_load_fu_368_p1 = ap_const_lv1_0))) then
                raddr_V <= trunc_ln97_fu_372_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((s_axi_aw_awvalid_read_read_fu_160_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                waddr_V <= trunc_ln45_fu_357_p1;
            end if;
        end if;
    end process;
    inner_reg1_V(9 downto 8) <= "00";
    inner_reg3_V(8) <= '0';
    inner_reg3_V(10) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    and_ln534_fu_500_p2 <= (s_axi_w_wvalid and ap_phi_mux_wready_V_phi_fu_246_p14);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_condition_141_assign_proc : process(ap_CS_fsm_state1, state_V_load_load_fu_368_p1, s_axi_ar_arvalid_read_read_fu_173_p2)
    begin
                ap_condition_141 <= ((ap_const_logic_1 = ap_CS_fsm_state1) and (s_axi_ar_arvalid_read_read_fu_173_p2 = ap_const_lv1_1) and (state_V_load_load_fu_368_p1 = ap_const_lv1_0));
    end process;


    ap_phi_mux_p_Val2_1_phi_fu_227_p14_assign_proc : process(waddr_V, ap_CS_fsm_state1, state1_V_load_load_fu_281_p1, s_axi_b_bready_read_read_fu_146_p2, s_axi_w_wvalid_read_read_fu_102_p2, trunc_ln45_fu_357_p1, s_axi_aw_awvalid_read_read_fu_160_p2)
    begin
        if (((s_axi_aw_awvalid_read_read_fu_160_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_p_Val2_1_phi_fu_227_p14 <= trunc_ln45_fu_357_p1;
        elsif ((((s_axi_w_wvalid_read_read_fu_102_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((s_axi_aw_awvalid_read_read_fu_160_p2 = ap_const_lv1_0) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((s_axi_w_wvalid_read_read_fu_102_p2 = ap_const_lv1_0) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((s_axi_b_bready_read_read_fu_146_p2 = ap_const_lv1_0) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((s_axi_b_bready_read_read_fu_146_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((state1_V_load_load_fu_281_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_phi_mux_p_Val2_1_phi_fu_227_p14 <= waddr_V;
        else 
            ap_phi_mux_p_Val2_1_phi_fu_227_p14 <= "XXXXX";
        end if; 
    end process;


    ap_phi_mux_wready_V_phi_fu_246_p14_assign_proc : process(ap_CS_fsm_state1, state1_V_load_load_fu_281_p1, s_axi_b_bready_read_read_fu_146_p2, s_axi_w_wvalid_read_read_fu_102_p2, s_axi_aw_awvalid_read_read_fu_160_p2)
    begin
        if (((s_axi_w_wvalid_read_read_fu_102_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_wready_V_phi_fu_246_p14 <= ap_const_lv1_1;
        elsif ((((s_axi_aw_awvalid_read_read_fu_160_p2 = ap_const_lv1_0) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((s_axi_aw_awvalid_read_read_fu_160_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((s_axi_w_wvalid_read_read_fu_102_p2 = ap_const_lv1_0) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((s_axi_b_bready_read_read_fu_146_p2 = ap_const_lv1_0) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((s_axi_b_bready_read_read_fu_146_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((state1_V_load_load_fu_281_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_phi_mux_wready_V_phi_fu_246_p14 <= ap_const_lv1_0;
        else 
            ap_phi_mux_wready_V_phi_fu_246_p14 <= "X";
        end if; 
    end process;


    ap_sig_allocacmp_inner_reg0_V_load_assign_proc : process(inner_reg0_V, ap_CS_fsm_state1, state1_V_load_load_fu_281_p1, s_axi_w_wvalid_read_read_fu_102_p2, zext_ln1348_1_fu_315_p1, p_Result_s_fu_323_p4)
    begin
        if (((p_Result_s_fu_323_p4 = ap_const_lv2_0) and (s_axi_w_wvalid_read_read_fu_102_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_inner_reg0_V_load <= zext_ln1348_1_fu_315_p1;
        else 
            ap_sig_allocacmp_inner_reg0_V_load <= inner_reg0_V;
        end if; 
    end process;


    ap_sig_allocacmp_inner_reg1_V_load_assign_proc : process(inner_reg1_V, ap_CS_fsm_state1, state1_V_load_load_fu_281_p1, s_axi_w_wvalid_read_read_fu_102_p2, p_Result_s_fu_323_p4, zext_ln1348_fu_311_p1)
    begin
        if (((p_Result_s_fu_323_p4 = ap_const_lv2_1) and (s_axi_w_wvalid_read_read_fu_102_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_inner_reg1_V_load <= zext_ln1348_fu_311_p1;
        else 
            ap_sig_allocacmp_inner_reg1_V_load <= inner_reg1_V;
        end if; 
    end process;


    ap_sig_allocacmp_inner_reg2_V_load_assign_proc : process(inner_reg2_V, ap_CS_fsm_state1, state1_V_load_load_fu_281_p1, s_axi_w_wvalid_read_read_fu_102_p2, zext_ln1348_1_fu_315_p1, p_Result_s_fu_323_p4)
    begin
        if (((p_Result_s_fu_323_p4 = ap_const_lv2_2) and (s_axi_w_wvalid_read_read_fu_102_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_inner_reg2_V_load <= zext_ln1348_1_fu_315_p1;
        else 
            ap_sig_allocacmp_inner_reg2_V_load <= inner_reg2_V;
        end if; 
    end process;


    ap_sig_allocacmp_inner_reg3_V_load_assign_proc : process(inner_reg3_V, ap_CS_fsm_state1, state1_V_load_load_fu_281_p1, s_axi_w_wvalid_read_read_fu_102_p2, p_Result_s_fu_323_p4, zext_ln1348_2_fu_319_p1)
    begin
        if ((not((p_Result_s_fu_323_p4 = ap_const_lv2_0)) and not((p_Result_s_fu_323_p4 = ap_const_lv2_1)) and (s_axi_w_wvalid_read_read_fu_102_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_inner_reg3_V_load <= zext_ln1348_2_fu_319_p1;
        else 
            ap_sig_allocacmp_inner_reg3_V_load <= inner_reg3_V;
        end if; 
    end process;

    icmp_ln870_fu_486_p2 <= "1" when (p_Result_4_fu_462_p4 = p_Result_5_fu_476_p4) else "0";
    p_Result_1_fu_388_p4 <= s_axi_ar_araddr(4 downto 3);
    p_Result_4_fu_462_p4 <= ap_phi_mux_p_Val2_1_phi_fu_227_p14(4 downto 3);
    p_Result_5_fu_476_p4 <= raddr_V(4 downto 3);
    p_Result_s_fu_323_p4 <= waddr_V(4 downto 3);
    ret_fu_305_p2 <= (trunc_ln38_fu_295_p1 and s_axi_w_wstrb);

    s_axi_ar_arready_assign_proc : process(ap_CS_fsm_state1, state_V_load_load_fu_368_p1, s_axi_ar_arvalid_read_read_fu_173_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (s_axi_ar_arvalid_read_read_fu_173_p2 = ap_const_lv1_1) and (state_V_load_load_fu_368_p1 = ap_const_lv1_0))) then 
            s_axi_ar_arready <= ap_const_lv1_1;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state1) and (s_axi_ar_arvalid_read_read_fu_173_p2 = ap_const_lv1_0) and (state_V_load_load_fu_368_p1 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (state_V_load_load_fu_368_p1 = ap_const_lv1_1)))) then 
            s_axi_ar_arready <= ap_const_lv1_0;
        else 
            s_axi_ar_arready <= "X";
        end if; 
    end process;

    s_axi_ar_arvalid_read_read_fu_173_p2 <= s_axi_ar_arvalid;

    s_axi_aw_awready_assign_proc : process(ap_CS_fsm_state1, state1_V_load_load_fu_281_p1, s_axi_w_wvalid_read_read_fu_102_p2, s_axi_aw_awvalid_read_read_fu_160_p2)
    begin
        if (((s_axi_aw_awvalid_read_read_fu_160_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            s_axi_aw_awready <= ap_const_lv1_1;
        elsif ((((s_axi_w_wvalid_read_read_fu_102_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((s_axi_aw_awvalid_read_read_fu_160_p2 = ap_const_lv1_0) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((s_axi_w_wvalid_read_read_fu_102_p2 = ap_const_lv1_0) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((state1_V_load_load_fu_281_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            s_axi_aw_awready <= ap_const_lv1_0;
        else 
            s_axi_aw_awready <= "X";
        end if; 
    end process;

    s_axi_aw_awvalid_read_read_fu_160_p2 <= s_axi_aw_awvalid;
    s_axi_b_bready_read_read_fu_146_p2 <= s_axi_b_bready;
    s_axi_b_bresp <= ap_const_lv2_0;

    s_axi_b_bvalid_assign_proc : process(ap_CS_fsm_state1, state1_V_load_load_fu_281_p1, s_axi_w_wvalid_read_read_fu_102_p2)
    begin
        if ((((s_axi_w_wvalid_read_read_fu_102_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((state1_V_load_load_fu_281_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((s_axi_w_wvalid_read_read_fu_102_p2 = ap_const_lv1_0) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            s_axi_b_bvalid <= ap_const_lv1_0;
        elsif (((state1_V_load_load_fu_281_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            s_axi_b_bvalid <= ap_const_lv1_1;
        else 
            s_axi_b_bvalid <= "X";
        end if; 
    end process;

    s_axi_r_rdata <= 
        select_ln534_fu_506_p3 when (ap_phi_mux_wready_V_phi_fu_246_p14(0) = '1') else 
        zext_ln674_fu_458_p1;
    s_axi_r_rready_read_read_fu_218_p2 <= s_axi_r_rready;
    s_axi_r_rresp <= ap_const_lv2_0;

    s_axi_r_rvalid_assign_proc : process(ap_CS_fsm_state1, state_V_load_load_fu_368_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
            if ((state_V_load_load_fu_368_p1 = ap_const_lv1_1)) then 
                s_axi_r_rvalid <= ap_const_lv1_1;
            elsif ((state_V_load_load_fu_368_p1 = ap_const_lv1_0)) then 
                s_axi_r_rvalid <= ap_const_lv1_0;
            else 
                s_axi_r_rvalid <= "X";
            end if;
        else 
            s_axi_r_rvalid <= "X";
        end if; 
    end process;


    s_axi_w_wready_assign_proc : process(ap_CS_fsm_state1, state1_V_load_load_fu_281_p1, s_axi_w_wvalid_read_read_fu_102_p2)
    begin
        if (((s_axi_w_wvalid_read_read_fu_102_p2 = ap_const_lv1_1) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            s_axi_w_wready <= ap_const_lv1_1;
        elsif ((((state1_V_load_load_fu_281_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((s_axi_w_wvalid_read_read_fu_102_p2 = ap_const_lv1_0) and (state1_V_load_load_fu_281_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((state1_V_load_load_fu_281_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            s_axi_w_wready <= ap_const_lv1_0;
        else 
            s_axi_w_wready <= "X";
        end if; 
    end process;

    s_axi_w_wvalid_read_read_fu_102_p2 <= s_axi_w_wvalid;
    select_ln124_fu_492_p3 <= 
        s_axi_w_wdata when (icmp_ln870_fu_486_p2(0) = '1') else 
        zext_ln674_fu_458_p1;
    select_ln534_fu_506_p3 <= 
        select_ln124_fu_492_p3 when (and_ln534_fu_500_p2(0) = '1') else 
        zext_ln674_fu_458_p1;
        sext_ln107_fu_402_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ap_sig_allocacmp_inner_reg2_V_load),11));

    state1_V_load_load_fu_281_p1 <= state1_V;
    state_V_load_load_fu_368_p1 <= state_V;
    trunc_ln38_fu_295_p1 <= s_axi_w_wdata(8 - 1 downto 0);
    trunc_ln45_fu_357_p1 <= s_axi_aw_awaddr(5 - 1 downto 0);
    trunc_ln97_fu_372_p1 <= s_axi_ar_araddr(5 - 1 downto 0);
    zext_ln101_fu_434_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_inner_reg0_V_load),12));
    zext_ln104_fu_420_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_inner_reg1_V_load),12));
    zext_ln107_fu_406_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln107_fu_402_p1),12));
    zext_ln1348_1_fu_315_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_fu_305_p2),9));
    zext_ln1348_2_fu_319_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_fu_305_p2),12));
    zext_ln1348_fu_311_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_fu_305_p2),11));
    zext_ln674_fu_458_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rdata_V),64));
end behav;
