// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="axi_slave_lite_reg_axi_slave_lite_reg,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu19eg-ffvc1760-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.015000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=63,HLS_SYN_LUT=380,HLS_VERSION=2020_2}" *)

module axi_slave_lite_reg (
        ap_clk,
        ap_rst,
        s_axi_ar_araddr,
        s_axi_ar_arready,
        s_axi_ar_arvalid,
        s_axi_aw_awaddr,
        s_axi_aw_awready,
        s_axi_aw_awvalid,
        s_axi_b_bresp,
        s_axi_b_bready,
        s_axi_b_bvalid,
        s_axi_r_rdata,
        s_axi_r_rresp,
        s_axi_r_rready,
        s_axi_r_rvalid,
        s_axi_w_wdata,
        s_axi_w_wstrb,
        s_axi_w_wready,
        s_axi_w_wvalid
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input  [63:0] s_axi_ar_araddr;
output  [0:0] s_axi_ar_arready;
input  [0:0] s_axi_ar_arvalid;
input  [63:0] s_axi_aw_awaddr;
output  [0:0] s_axi_aw_awready;
input  [0:0] s_axi_aw_awvalid;
output  [1:0] s_axi_b_bresp;
input  [0:0] s_axi_b_bready;
output  [0:0] s_axi_b_bvalid;
output  [63:0] s_axi_r_rdata;
output  [1:0] s_axi_r_rresp;
input  [0:0] s_axi_r_rready;
output  [0:0] s_axi_r_rvalid;
input  [63:0] s_axi_w_wdata;
input  [7:0] s_axi_w_wstrb;
output  [0:0] s_axi_w_wready;
input  [0:0] s_axi_w_wvalid;

reg[0:0] s_axi_ar_arready;
reg[0:0] s_axi_aw_awready;
reg[0:0] s_axi_b_bvalid;
reg[0:0] s_axi_r_rvalid;
reg[0:0] s_axi_w_wready;

reg   [1:0] state1_V;
reg   [4:0] waddr_V;
reg   [8:0] inner_reg0_V;
reg   [10:0] inner_reg1_V;
reg   [8:0] inner_reg2_V;
reg   [11:0] inner_reg3_V;
reg   [0:0] state_V;
reg   [4:0] raddr_V;
reg   [11:0] rdata_V;
reg   [4:0] ap_phi_mux_p_Val2_1_phi_fu_227_p14;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [1:0] state1_V_load_load_fu_281_p1;
wire   [0:0] s_axi_b_bready_read_read_fu_146_p2;
wire   [0:0] s_axi_w_wvalid_read_read_fu_102_p2;
wire   [4:0] trunc_ln45_fu_357_p1;
wire   [0:0] s_axi_aw_awvalid_read_read_fu_160_p2;
reg   [0:0] ap_phi_mux_wready_V_phi_fu_246_p14;
wire   [8:0] zext_ln1348_1_fu_315_p1;
wire   [1:0] p_Result_s_fu_323_p4;
reg   [8:0] ap_sig_allocacmp_inner_reg0_V_load;
wire   [0:0] state_V_load_load_fu_368_p1;
wire   [0:0] s_axi_ar_arvalid_read_read_fu_173_p2;
wire   [1:0] p_Result_1_fu_388_p4;
wire   [10:0] zext_ln1348_fu_311_p1;
reg   [10:0] ap_sig_allocacmp_inner_reg1_V_load;
reg   [8:0] ap_sig_allocacmp_inner_reg2_V_load;
wire   [11:0] zext_ln1348_2_fu_319_p1;
reg   [11:0] ap_sig_allocacmp_inner_reg3_V_load;
wire   [0:0] s_axi_r_rready_read_read_fu_218_p2;
wire   [4:0] trunc_ln97_fu_372_p1;
wire   [0:0] and_ln534_fu_500_p2;
wire   [11:0] zext_ln107_fu_406_p1;
wire   [11:0] zext_ln104_fu_420_p1;
wire   [11:0] zext_ln101_fu_434_p1;
wire   [7:0] trunc_ln38_fu_295_p1;
wire   [7:0] ret_fu_305_p2;
wire  signed [10:0] sext_ln107_fu_402_p1;
wire   [1:0] p_Result_4_fu_462_p4;
wire   [1:0] p_Result_5_fu_476_p4;
wire   [0:0] icmp_ln870_fu_486_p2;
wire   [63:0] zext_ln674_fu_458_p1;
wire   [63:0] select_ln124_fu_492_p3;
wire   [63:0] select_ln534_fu_506_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_condition_141;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 state1_V = 2'd0;
#0 waddr_V = 5'd0;
#0 inner_reg0_V = 9'd291;
#0 inner_reg1_V = 11'd1110;
#0 inner_reg2_V = 9'd393;
#0 inner_reg3_V = 12'd2748;
#0 state_V = 1'd0;
#0 raddr_V = 5'd0;
#0 rdata_V = 12'd0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_141)) begin
        if ((p_Result_1_fu_388_p4 == 2'd3)) begin
            rdata_V <= ap_sig_allocacmp_inner_reg3_V_load;
        end else if ((p_Result_1_fu_388_p4 == 2'd0)) begin
            rdata_V <= zext_ln101_fu_434_p1;
        end else if ((p_Result_1_fu_388_p4 == 2'd1)) begin
            rdata_V <= zext_ln104_fu_420_p1;
        end else if ((p_Result_1_fu_388_p4 == 2'd2)) begin
            rdata_V <= zext_ln107_fu_406_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((s_axi_aw_awvalid_read_read_fu_160_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state1)) | ((s_axi_w_wvalid_read_read_fu_102_p2 == 1'd0) & (state1_V_load_load_fu_281_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        state1_V <= 2'd1;
    end else if (((s_axi_b_bready_read_read_fu_146_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        state1_V <= 2'd0;
    end else if ((((s_axi_w_wvalid_read_read_fu_102_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1)) | ((s_axi_b_bready_read_read_fu_146_p2 == 1'd0) & (state1_V_load_load_fu_281_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1)))) begin
        state1_V <= 2'd2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((s_axi_r_rready_read_read_fu_218_p2 == 1'd1) & (state_V_load_load_fu_368_p1 == 1'd1))) begin
            state_V <= 1'd0;
        end else if (((s_axi_ar_arvalid_read_read_fu_173_p2 == 1'd1) & (state_V_load_load_fu_368_p1 == 1'd0))) begin
            state_V <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((p_Result_s_fu_323_p4 == 2'd0) & (s_axi_w_wvalid_read_read_fu_102_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        inner_reg0_V <= zext_ln1348_1_fu_315_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((p_Result_s_fu_323_p4 == 2'd1) & (s_axi_w_wvalid_read_read_fu_102_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        inner_reg1_V[7 : 0] <= zext_ln1348_fu_311_p1[7 : 0];
inner_reg1_V[10] <= zext_ln1348_fu_311_p1[10];
    end
end

always @ (posedge ap_clk) begin
    if (((p_Result_s_fu_323_p4 == 2'd2) & (s_axi_w_wvalid_read_read_fu_102_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        inner_reg2_V <= zext_ln1348_1_fu_315_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(p_Result_s_fu_323_p4 == 2'd0) & ~(p_Result_s_fu_323_p4 == 2'd1) & (s_axi_w_wvalid_read_read_fu_102_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        inner_reg3_V[7 : 0] <= zext_ln1348_2_fu_319_p1[7 : 0];
inner_reg3_V[9] <= zext_ln1348_2_fu_319_p1[9];
inner_reg3_V[11] <= zext_ln1348_2_fu_319_p1[11];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (s_axi_ar_arvalid_read_read_fu_173_p2 == 1'd1) & (state_V_load_load_fu_368_p1 == 1'd0))) begin
        raddr_V <= trunc_ln97_fu_372_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((s_axi_aw_awvalid_read_read_fu_160_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        waddr_V <= trunc_ln45_fu_357_p1;
    end
end

always @ (*) begin
    if (((s_axi_aw_awvalid_read_read_fu_160_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_phi_mux_p_Val2_1_phi_fu_227_p14 = trunc_ln45_fu_357_p1;
    end else if ((((s_axi_w_wvalid_read_read_fu_102_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1)) | ((s_axi_aw_awvalid_read_read_fu_160_p2 == 1'd0) & (state1_V_load_load_fu_281_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state1)) | ((s_axi_w_wvalid_read_read_fu_102_p2 == 1'd0) & (state1_V_load_load_fu_281_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1)) | ((s_axi_b_bready_read_read_fu_146_p2 == 1'd0) & (state1_V_load_load_fu_281_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1)) | ((s_axi_b_bready_read_read_fu_146_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1)) | ((state1_V_load_load_fu_281_p1 == 2'd3) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_phi_mux_p_Val2_1_phi_fu_227_p14 = waddr_V;
    end else begin
        ap_phi_mux_p_Val2_1_phi_fu_227_p14 = 'bx;
    end
end

always @ (*) begin
    if (((s_axi_w_wvalid_read_read_fu_102_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_phi_mux_wready_V_phi_fu_246_p14 = 1'd1;
    end else if ((((s_axi_aw_awvalid_read_read_fu_160_p2 == 1'd0) & (state1_V_load_load_fu_281_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state1)) | ((s_axi_aw_awvalid_read_read_fu_160_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state1)) | ((s_axi_w_wvalid_read_read_fu_102_p2 == 1'd0) & (state1_V_load_load_fu_281_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1)) | ((s_axi_b_bready_read_read_fu_146_p2 == 1'd0) & (state1_V_load_load_fu_281_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1)) | ((s_axi_b_bready_read_read_fu_146_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1)) | ((state1_V_load_load_fu_281_p1 == 2'd3) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_phi_mux_wready_V_phi_fu_246_p14 = 1'd0;
    end else begin
        ap_phi_mux_wready_V_phi_fu_246_p14 = 'bx;
    end
end

always @ (*) begin
    if (((p_Result_s_fu_323_p4 == 2'd0) & (s_axi_w_wvalid_read_read_fu_102_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_inner_reg0_V_load = zext_ln1348_1_fu_315_p1;
    end else begin
        ap_sig_allocacmp_inner_reg0_V_load = inner_reg0_V;
    end
end

always @ (*) begin
    if (((p_Result_s_fu_323_p4 == 2'd1) & (s_axi_w_wvalid_read_read_fu_102_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_inner_reg1_V_load = zext_ln1348_fu_311_p1;
    end else begin
        ap_sig_allocacmp_inner_reg1_V_load = inner_reg1_V;
    end
end

always @ (*) begin
    if (((p_Result_s_fu_323_p4 == 2'd2) & (s_axi_w_wvalid_read_read_fu_102_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_inner_reg2_V_load = zext_ln1348_1_fu_315_p1;
    end else begin
        ap_sig_allocacmp_inner_reg2_V_load = inner_reg2_V;
    end
end

always @ (*) begin
    if ((~(p_Result_s_fu_323_p4 == 2'd0) & ~(p_Result_s_fu_323_p4 == 2'd1) & (s_axi_w_wvalid_read_read_fu_102_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_inner_reg3_V_load = zext_ln1348_2_fu_319_p1;
    end else begin
        ap_sig_allocacmp_inner_reg3_V_load = inner_reg3_V;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (s_axi_ar_arvalid_read_read_fu_173_p2 == 1'd1) & (state_V_load_load_fu_368_p1 == 1'd0))) begin
        s_axi_ar_arready = 1'd1;
    end else if ((((1'b1 == ap_CS_fsm_state1) & (s_axi_ar_arvalid_read_read_fu_173_p2 == 1'd0) & (state_V_load_load_fu_368_p1 == 1'd0)) | ((1'b1 == ap_CS_fsm_state1) & (state_V_load_load_fu_368_p1 == 1'd1)))) begin
        s_axi_ar_arready = 1'd0;
    end else begin
        s_axi_ar_arready = 'bx;
    end
end

always @ (*) begin
    if (((s_axi_aw_awvalid_read_read_fu_160_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        s_axi_aw_awready = 1'd1;
    end else if ((((s_axi_w_wvalid_read_read_fu_102_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1)) | ((s_axi_aw_awvalid_read_read_fu_160_p2 == 1'd0) & (state1_V_load_load_fu_281_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state1)) | ((s_axi_w_wvalid_read_read_fu_102_p2 == 1'd0) & (state1_V_load_load_fu_281_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1)) | ((state1_V_load_load_fu_281_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1)))) begin
        s_axi_aw_awready = 1'd0;
    end else begin
        s_axi_aw_awready = 'bx;
    end
end

always @ (*) begin
    if ((((s_axi_w_wvalid_read_read_fu_102_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1)) | ((state1_V_load_load_fu_281_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state1)) | ((s_axi_w_wvalid_read_read_fu_102_p2 == 1'd0) & (state1_V_load_load_fu_281_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        s_axi_b_bvalid = 1'd0;
    end else if (((state1_V_load_load_fu_281_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        s_axi_b_bvalid = 1'd1;
    end else begin
        s_axi_b_bvalid = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((state_V_load_load_fu_368_p1 == 1'd1)) begin
            s_axi_r_rvalid = 1'd1;
        end else if ((state_V_load_load_fu_368_p1 == 1'd0)) begin
            s_axi_r_rvalid = 1'd0;
        end else begin
            s_axi_r_rvalid = 'bx;
        end
    end else begin
        s_axi_r_rvalid = 'bx;
    end
end

always @ (*) begin
    if (((s_axi_w_wvalid_read_read_fu_102_p2 == 1'd1) & (state1_V_load_load_fu_281_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        s_axi_w_wready = 1'd1;
    end else if ((((state1_V_load_load_fu_281_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state1)) | ((s_axi_w_wvalid_read_read_fu_102_p2 == 1'd0) & (state1_V_load_load_fu_281_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1)) | ((state1_V_load_load_fu_281_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1)))) begin
        s_axi_w_wready = 1'd0;
    end else begin
        s_axi_w_wready = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln534_fu_500_p2 = (s_axi_w_wvalid & ap_phi_mux_wready_V_phi_fu_246_p14);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_condition_141 = ((1'b1 == ap_CS_fsm_state1) & (s_axi_ar_arvalid_read_read_fu_173_p2 == 1'd1) & (state_V_load_load_fu_368_p1 == 1'd0));
end

assign icmp_ln870_fu_486_p2 = ((p_Result_4_fu_462_p4 == p_Result_5_fu_476_p4) ? 1'b1 : 1'b0);

assign p_Result_1_fu_388_p4 = {{s_axi_ar_araddr[4:3]}};

assign p_Result_4_fu_462_p4 = {{ap_phi_mux_p_Val2_1_phi_fu_227_p14[4:3]}};

assign p_Result_5_fu_476_p4 = {{raddr_V[4:3]}};

assign p_Result_s_fu_323_p4 = {{waddr_V[4:3]}};

assign ret_fu_305_p2 = (trunc_ln38_fu_295_p1 & s_axi_w_wstrb);

assign s_axi_ar_arvalid_read_read_fu_173_p2 = s_axi_ar_arvalid;

assign s_axi_aw_awvalid_read_read_fu_160_p2 = s_axi_aw_awvalid;

assign s_axi_b_bready_read_read_fu_146_p2 = s_axi_b_bready;

assign s_axi_b_bresp = 2'd0;

assign s_axi_r_rdata = ((ap_phi_mux_wready_V_phi_fu_246_p14[0:0] == 1'b1) ? select_ln534_fu_506_p3 : zext_ln674_fu_458_p1);

assign s_axi_r_rready_read_read_fu_218_p2 = s_axi_r_rready;

assign s_axi_r_rresp = 2'd0;

assign s_axi_w_wvalid_read_read_fu_102_p2 = s_axi_w_wvalid;

assign select_ln124_fu_492_p3 = ((icmp_ln870_fu_486_p2[0:0] == 1'b1) ? s_axi_w_wdata : zext_ln674_fu_458_p1);

assign select_ln534_fu_506_p3 = ((and_ln534_fu_500_p2[0:0] == 1'b1) ? select_ln124_fu_492_p3 : zext_ln674_fu_458_p1);

assign sext_ln107_fu_402_p1 = $signed(ap_sig_allocacmp_inner_reg2_V_load);

assign state1_V_load_load_fu_281_p1 = state1_V;

assign state_V_load_load_fu_368_p1 = state_V;

assign trunc_ln38_fu_295_p1 = s_axi_w_wdata[7:0];

assign trunc_ln45_fu_357_p1 = s_axi_aw_awaddr[4:0];

assign trunc_ln97_fu_372_p1 = s_axi_ar_araddr[4:0];

assign zext_ln101_fu_434_p1 = ap_sig_allocacmp_inner_reg0_V_load;

assign zext_ln104_fu_420_p1 = ap_sig_allocacmp_inner_reg1_V_load;

assign zext_ln107_fu_406_p1 = $unsigned(sext_ln107_fu_402_p1);

assign zext_ln1348_1_fu_315_p1 = ret_fu_305_p2;

assign zext_ln1348_2_fu_319_p1 = ret_fu_305_p2;

assign zext_ln1348_fu_311_p1 = ret_fu_305_p2;

assign zext_ln674_fu_458_p1 = rdata_V;

always @ (posedge ap_clk) begin
    inner_reg1_V[9:8] <= 2'b00;
    inner_reg3_V[8] <= 1'b0;
    inner_reg3_V[10] <= 1'b0;
end

endmodule //axi_slave_lite_reg
